---
title: "Going Critical: Thermal Maximum"
description: |
  A short description of the post.
author:
  - name: Alex Mendelson
    url: {}
date: 2024-06-27
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(reticulate)
library(tidyverse)
library(car)
library(knitr)
```


```{r expSetup, include=TRUE, echo=TRUE}
sourceCultures <- data.frame(
  Source = c("Stock", "Pop1", "Pop1", "Pop1", "Pop1", "Pop1"),
  CloneID = c("1.2", "1.5", "1.7", "2.3", "2.4", "2.5"),
  Count = c(25,133,31,103,77,71))

countVol = 0.3         # volume counted in plate
finalDensity = 80      # rotifers per mL
finalVolume = 0.3      # stock culture volume, mL

# The volume of source culture to be transferred to destination in microliters (uL)
VolumeFinal <- ((finalDensity * finalVolume)/ (sourceCultures$Count / countVol)) *1000 
sourceCultures <- cbind(sourceCultures, VolumeFinal)

# I couldn't find any 10 mL pipette tips, so I included this column to easily use the 5 mL pipette twice
VolFinHalf <- sourceCultures$VolumeFinal / 2
sourceCultures <- cbind(sourceCultures, VolFinHalf)

# The volume of media (in uL) to be added into each experimental well for the total volume to remain consistent among clones
VolAdd <- (300 - sourceCultures$VolumeFinal)
sourceCultures <- cbind(sourceCultures, VolAdd)

kable(sourceCultures)

randomizedMatrix <- data.frame(
  Well = c("A1", "A2", "A3", "A4", "A5", "A6", 
           "B1", "B2", "B3", "B4", "B5", "B6", 
           "C1", "C2", "C3", "C4", "C5", "C6", 
           "D1", "D2", "D3", "D4", "D5", "D6"),
  CloneID = c("2.4", "2.5", "1.2", "2.3", "2.5", "1.7", 
         "2.3", "1.5", "1.2", "2.5", "1.7", "1.5", 
         "1.7", "1.2", "2.4", "1.5", "1.7", "2.3", 
         "2.3", "1.5", "2.4", "2.5", "1.2", "2.4"), 
  Rep = c("a", "a", "a", "a", "b", "a",
          "b", "a", "b", "c", "b", "b",
          "c", "c", "b", "c", "d", "c",
          "d", "d", "c", "d", "d", "d")
)

expSetup <- merge(randomizedMatrix, sourceCultures[, c("CloneID", "VolumeFinal", "VolAdd")], by = "CloneID", all.x = TRUE)

kable(expSetup)

```
